Greeting.create!(greeting: 'Hello, Otto!')
Greeting.create!(greeting: 'Konbawa, Otto!')
Greeting.create!(greeting: 'Ekaro, Otto!')
Greeting.create!(greeting: 'Hola, Otto!')
Greeting.create!(greeting: 'Bwanji, Otto!')
